export const NOTFIFICATION_BELL_ICON = 'NOTFIFICATION_BELL_ICON';
export const ENTILEMENT_TAKEN_LEAVE_COUNT = 'ENTILEMENT_TAKEN_LEAVE_COUNT';
export const ENTILEMENT_ALL_LEAVE_COUNT = 'ENTILEMENT_ALL_LEAVE_COUNT';
export const USER_PROFILE_PIC = 'USER_PROFILE_PIC';
export const EMPLOYEE_LEAVE_REQUEST_LIST = 'EMPLOYEE_LEAVE_REQUEST_LIST';
export const LEAVE_REQUEST_ROW = 'LEAVE_REQUEST_ROW';
