const TID = 'test:id/';

export const TID_NOTFIFICATION_BELL_ICON = `${TID}NOTFIFICATION_BELL_ICON`;
export const TID_NOTFIFICATION_LIST = `${TID}NOTFIFICATION_LIST`;
export const TID_NOTFIFICATION_ROW = `${TID}TID_NOTFIFICATION_ROW`;

export const TID_ENTILEMENT_TAKEN_LEAVE_COUNT = `${TID}ENTILEMENT_TAKEN_LEAVE_COUNT`;
export const TID_ENTILEMENT_ALL_LEAVE_COUNT = `${TID}ENTILEMENT_ALL_LEAVE_COUNT`;

export const TID_USER_PROFILE_PIC = `${TID}USER_PROFILE_PIC`;

export const TID_EMPLOYEE_LEAVE_REQUEST_LIST = `${TID}EMPLOYEE_LEAVE_REQUEST_LIST`;
export const TID_EMPLOYEE_LEAVE_REQUEST_ROW = `${TID}TID_EMPLOYEE_LEAVE_REQUEST_ROW`;

export const TID_MANAGER_LEAVE_REQUEST_LIST = `${TID}MANAGER_LEAVE_REQUEST_LIST`;
export const TID_MANAGER_LEAVE_REQUEST_ROW = `${TID}TID_MANAGER_LEAVE_REQUEST_ROW`;

export const TID_MANAGER_PENDING_LEAVE_MODAL = `${TID}TID_MANAGER_PENDING_LEAVE_MODAL`;
export const TID_MANAGER_APPROVED_LEAVE_MODAL = `${TID}TID_MANAGER_APPROVED_LEAVE_MODAL`;
export const TID_MANAGER_DENIED_LEAVE_MODAL = `${TID}TID_MANAGER_DENIED_LEAVE_MODAL`;
export const TID_MANAGER_LEAVE_INFORMATION = `${TID}TID_MANAGER_LEAVE_INFORMATION`;
export const TID_MANAGER_DECLINE_LEAVE_MODAL = `${TID}TID_MANAGER_DECLINE_LEAVE_MODAL`;
export const TID_MANAGER_CANCELLED_LEAVE_MODAL = `${TID}TID_MANAGER_CANCELLED_LEAVE_MODAL`;
export const TID_MANAGER_REVOKE_LEAVE_MODAL = `${TID}TID_MANAGER_REVOKE_LEAVE_MODAL`;

export const TID_EMPLOYEE_APPLY_LEAVE_MODAL = `${TID}TID_EMPLOYEE_APPLY_LEAVE_MODAL`;
export const TID_EMPLOYEE_CHOSE_DATE_MODAL = `${TID}TID_EMPLOYEE_CHOSE_DATE_MODAL`;
export const TID_EMPLOYEE_PENDING_LEAVE_MODAL = `${TID}TID_EMPLOYEE_PENDING_LEAVE_MODAL`;
export const TID_EMPLOYEE_LEAVE_INFORMATION = `${TID}TID_EMPLOYEE_LEAVE_INFORMATION`;
export const TID_EMPLOYEE_CANCEL_REQUEST_MODAL = `${TID}TID_EMPLOYEE_CANCEL_REQUEST_MODAL`;
export const TID_EMPLOYEE_CANCELLED_LEAVE_MODAL = `${TID}TID_EMPLOYEE_CANCELLED_LEAVE_MODAL`;
export const TID_EMPLOYEE_DENIED_LEAVE_MODAL = `${TID}TID_EMPLOYEE_DENIED_LEAVE_MODAL`;
export const TID_EMPLOYEE_APPROVED_LEAVE_MODAL = `${TID}TID_EMPLOYEE_APPROVED_LEAVE_MODAL`;
export const TID_EMPLOYEE_REVOKE_REQUEST_MODAL = `${TID}TID_EMPLOYEE_REVOKE_REQUEST_MODAL`;

export const TID_LEAVE_STATUS_TYPE = `${TID}TID_LEAVE_STATUS_TYPE`;
export const TID_LEAVE_STATUS_STATUS = `${TID}TID_LEAVE_STATUS_STATUS`;
export const TID_LEAVE_STATUS_DURATION = `${TID}TID_LEAVE_STATUS_DURATION`;
export const TID_LEAVE_STATUS_RECIPIENT = `${TID}TID_LEAVE_STATUS_RECIPIENT`;
export const TID_LEAVE_STATUS_MEMBER = `${TID}TID_LEAVE_STATUS_MEMBER`;
