const TID = 'test:id/';

export const TID_NOTFIFICATION_BELL_ICON = `${TID}NOTFIFICATION_BELL_ICON`;
export const TID_ENTILEMENT_TAKEN_LEAVE_COUNT = `${TID}ENTILEMENT_TAKEN_LEAVE_COUNT`;
export const TID_ENTILEMENT_ALL_LEAVE_COUNT = `${TID}ENTILEMENT_ALL_LEAVE_COUNT`;
export const TID_USER_PROFILE_PIC = `${TID}USER_PROFILE_PIC`;
export const TID_EMPLOYEE_LEAVE_REQUEST_LIST = `${TID}EMPLOYEE_LEAVE_REQUEST_LIST`;
export const TID_LEAVE_REQUEST_ROW = 'LEAVE_REQUEST_ROW';
