-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtB7Nlyi55ZDoizGt
FFPYk/KEq1fIAUeu61HJml3MWECgCgYIKoZIzj0DAQehRANCAAQ4Zfph6DEaTQow
yJjd/ASKjGCFlOTIEzTgixlt/CBLD11YhxTOcnkLyE6pS8px7TtUzrYDVvoqiDAy
Y7wEazI1
-----END PRIVATE KEY-----